### ISSUE TITLE
Add data augmentation scripts to work natively in PyHa

### ISSUE THREAD

**Issue by sprestrelski** [UCSD-E4E/PyHa#137]
Add ability for the [data augmentation scripts](https://github.com/UCSD-E4E/passive-acoustic-biodiversity/tree/master/DSP_Tools) that can filter and scale audio, as described in [this paper](https://kastner.ucsd.edu/ryan/wp-content/uploads/sites/5/2020/06/admin/aasi.pdf) and developed by previous members of the project, to work natively in PyHa.

**Comment by JacobGlennAyers** [comment]
All of those scripts can be found in this Microfaune training pipeline: https://github.com/UCSD-E4E/AID_ICML_2021/blob/master/Train_Microfaune_RNN.py

With that being said, I feel that we would need to first introduce the scripts to retrain the relevant neural networks used (TweetyNET, Microfaune, and maybe BirdNET in the future if they release it) because I don't see a purpose of data augmentation without those pipelines being available.

**Comment by sprestrelski** [comment]
That makes sense. The REU2022 team is working on retraining pipelines for OpenSoundscape, TweetyNet, and [BirdNET-Analyzer](https://github.com/kahst/BirdNET-Analyzer/) with the idea that we can integrate them into PyHa later. Microfaune was put on the backburner because of a TensorFlow 1.0 -> 2.0 compatibility issue

**Comment by sprestrelski** [comment]
I don't think this fits within the scope of PyHa and should instead be in https://github.com/UCSD-E4E/acoustic-multiclass-training
